// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUCxiVnl2K7WAwHmeLb7gGrgSBLe5MTpQ',
    appId: '1:641621420643:web:3942085f60a475ea45a656',
    messagingSenderId: '641621420643',
    projectId: 'hrm-jmm',
    authDomain: 'hrm-jmm.firebaseapp.com',
    storageBucket: 'hrm-jmm.appspot.com',
    measurementId: 'G-3S743LFMF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl38nEmIYl-KyIxEIaSTOT2TnzYnDtX_k',
    appId: '1:641621420643:android:8b6a814250f9256345a656',
    messagingSenderId: '641621420643',
    projectId: 'hrm-jmm',
    storageBucket: 'hrm-jmm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCtOvpuvFdW5iAc4BjIAfAhdXoPwoEXmc',
    appId: '1:641621420643:ios:8cd8b650eb60ab6f45a656',
    messagingSenderId: '641621420643',
    projectId: 'hrm-jmm',
    storageBucket: 'hrm-jmm.appspot.com',
    iosBundleId: 'com.example.hrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCtOvpuvFdW5iAc4BjIAfAhdXoPwoEXmc',
    appId: '1:641621420643:ios:f0b993feb939593045a656',
    messagingSenderId: '641621420643',
    projectId: 'hrm-jmm',
    storageBucket: 'hrm-jmm.appspot.com',
    iosBundleId: 'com.example.hrm.RunnerTests',
  );
}
